environment:
  SLACK_TOKEN: ${SLACK_TOKEN}
packages:
  - name: monitor-snapshot
    actions:
      - name: main
        runtime: 'python:default'
        triggers:
          - name: trigger-snapshot
            sourceType: scheduler
            sourceDetails:
              cron: "0 8 * * *"
              withBody:
                name: 'sammy'
