FROM fedora:36

# Install dependencies
RUN dnf install -y \
    docker \
    ruby \
    ruby-devel \
    make \
    gcc \
    && dnf clean all

# Install required Ruby packages
RUN gem install \
    docker-api \
    slack-ruby-client
