FROM fedora:36

RUN dnf -y install dnf-plugins-core-4.3.1 && \
    dnf config-manager \
        --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo && dnf clean all

RUN dnf install -y \
    docker-ce-3:23.0.2 \
    docker-ce-cli-1:23.0.2 \
    containerd.io-1.6.19 \
    docker-buildx-plugin-0.10.4 \
    ruby-3.1.3 \
    ruby-devel-3.1.3 \
    make-4.3 \
    gcc-12.2.1 \
    && dnf clean all

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock ./

RUN gem install bundler:2.3.4 && bundle install
