FROM fedora:36

RUN dnf install -y \
    docker \
    ruby \
    ruby-devel \
    make \
    gcc \
    && dnf clean all

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock ./

RUN gem install bundler:2.3.4 && bundle install
