FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install --no-install-recommends -y docker ruby make gcc build-essential ruby-dev curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock health_check.sh sync_check_process.rb sync_check.rb sync_check.toml ./
COPY ruby_common ruby_common

RUN gem install bundler && bundle install
