name: 'Linting'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  Lint_ansible:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install test dependencies.
      run: pip3 install ansible-lint

    - name: Install Ansible-galaxy Collection
      run: |
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install community.general
    - name: Lint code.
      working-directory: Ansible
      run: ansible-lint

  lint_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
           path: ~/.tflint.d/plugins
           key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
           tflint_version: v0.44.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        working-directory: ./Terraform
        run: tflint --init

      - name: Run TFLint
        working-directory: ./Terraform
        run: tflint -f compact
        