env:
  commonjs: true
  es2021: true
  shared-node-browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
plugins:
  - "@typescript-eslint"
