#!/bin/bash

# shellcheck source=/dev/null
source ~/.forest_env
cd "$BASE_FOLDER" || exit
while :
do
    flock -n /tmp/mainnet.lock -c "ruby daily_snapshot.rb mainnet > logs/mainnet_log.txt 2>&1"
    flock -n /tmp/mainnet_filops.lock -c "./upload_filops_snapshot.sh mainnet > logs/filops_mainnet_log.txt 2>&1"
done
