FROM ubuntu:22.04

RUN apt-get install -y --no-install-recommends \
    docker \
    ruby \
    ruby-devel \
    make \
    gcc

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock health_check.sh sync_check_process.rb sync_check.rb sync_check.toml ./
COPY ruby_common ruby_common

RUN gem install bundler && bundle install
