---
# tasks file for roles/node_exporter
- name: Check if node_exporter is present
  ansible.builtin.stat:
    path: "{{ node_exporter_bin }}"
  register: node_exporter_binary
  changed_when: false

- name: Create a user for node_exporter
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    append: true
    shell: "/usr/sbin/nologin"
    system: true
    create_home: false
    home: /

- name: Create node_exporter config dir
  ansible.builtin.file:
    path: "{{ node_exporter_dir_conf }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0644"

- name: Set-up Exporter
  block:
    - name: If node_exporter exists get version
      ansible.builtin.shell: >-
        set -o pipefail &&
        node_exporter --version | awk '{print $3}'
      args:
        executable: /bin/bash
      when: _check_node_exporter_present.stat.exists
      changed_when: false
      register: node_exporter_service_version

    - name: Set node_exporter_version fact
      ansible.builtin.set_fact:
        node_exporter_version: "{{ _get_node_exporter_version.stdout }}"
      when: _check_node_exporter_present.stat.exists

    - name: Download node_exporter binary if it does not exist or version is different
      ansible.builtin.unarchive:
        src: "{{ node_exporter_src }}"
        dest: "/tmp/"
        remote_src: true
        validate_certs: false
      when: not node_exporter_binary.stat.exists or not node_exporter_service_version.stdout == node_exporter_version

    - name: Move the binary to the node_exporter destination
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_bin }}"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: "0755"
        remote_src: true
      when: not node_exporter_binary.stat.exists or not node_exporter_service_version.stdout == node_exporter_version

    - name: Clean up
      ansible.builtin.file:
        path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        state: absent

    - name: Install node_exporter service
      ansible.builtin.template:
        src: "node_exporter_service.j2"
        dest: "{{ node_exporter_service_dest }}"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: "0755"
      notify: Reload_daemon_and_restart_node_exporter

    - name: Flush Handler
      ansible.builtin.meta: flush_handlers

    - name: Ensure Node Exporter service is always started
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: true

- name: Allow access to Node Exporter port
  become: true
  community.general.ufw:
    rule: allow
    port: "9100"
    proto: tcp
    state: enabled
