---
# tasks file for roles/node-exporter

- name: check in node export is present 
  stat:
    path: "{{ node_exporter_bin }}"
  register: _check_node_exporter_present

- name: create a user for node exporter
  user: 
    name: "{{ node_exporter_user }}"
    append: true
    shell: "/usr/sbin/nologin"
    system: true
    create_home: false
    home: /
   
- name: create node export config dir
  file: 
     path: "{{ node_exporter_dir_conf }}"
     state: directory
     owner: "{{ node_exporter_user }}"
     group: "{{ node_exporter_group }}"

- block:
  - name: if node exporter exist get version
    shell: "cat /etc/system/system/node_exporter.service | grep Version | sed s/'.*Version '//g"
    when: _check_node_exporter_present.stat.exists == true
    changed_when: false 
    register: _get_node_exporter_version

  - name: Download node_exporter binary to local folder and unzip 
    unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest:  /tmp/
        remote_src: yes
        validate_certs: no
    when: _check_node_exporter_present.stat.exists == false or not _get_node_exporter_version.stdout == node_exporter_version  

  - name: move the binary to the node-exporter destination
    copy: 
      src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
      dest: "{{ node_exporter_bin }}"
      owner: "{{ node_exporter_user }}"
      group: "{{ node_exporter_group }}"
      mode: 0755
      remote_src: yes
    when: _check_node_exporter_present.stat.exists == false or not _get_node_exporter_version.stdout == node_exporter_version

  - name: clean
    file: 
      path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
      state: absent

  - name: install node exporter service
    template: 
      src: "node_exporter_service.j2"
      dest: "{{ node_exporter_service_dest }}"
      owner: "root"
      group: "root"
      mode: 0755   
    notify: reload_daemon_and_restart_node_exporter

  - meta: flush_handlers

  - name: Ensure Node Exporter service always started 
    systemd:
      name: node_exporter
      state: started
      enabled: yes 

- name: Allow access to Node exporter port  
  become: true
  ufw:
    rule: allow
    port: '9100'
    proto: tcp
    state: enabled 

    

