name: Configure Observability for Forest Infrastructure Nodes on DigitalOcean with Ansible

description: |
  This action sets up and install the new relic agents for Forest Infrastructure node on Digitalocean
inputs:
  ssh_private_key:
    description: 'The SSH private key to use for configuring Ansible'
    required: true
  working_directory:
    description: 'The working directory of a certain ansible operation'
    required: true
  new_relic_api_key:
    description: 'The api key secret for new relic operations'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Forest ${{ inputs.chain }} Host File
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: download
      uses: actions/download-artifact@v2
      with:
        name: hosts
        path: ansible/

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set-up Action
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ansible==7.4.0
        
    - name: Configure ssh-agent
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}   

    - name: Install Ansible Playbook Requirement
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: ansible-galaxy install -r requirements.yml
      shell: bash

    - name: Run Ansible To Install and Set-Up  New-Relic Agent
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: ansible-playbook install_newrelic_infra_agent.yml
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        ANSIBLE_CONFIG: ansible.cfg
        NEW_RELIC_API_KEY: ${{ inputs.new_relic_api_key }}
