FROM fedora:38

RUN dnf install -y \
    docker \
    ruby \
    ruby-devel \
    make \
    gcc \
    && dnf clean all

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock health_check.sh sync_check_process.rb sync_check.rb sync_check.toml ./
COPY ruby_common ruby_common

RUN gem install bundler && bundle install
