FROM fedora:36

RUN dnf -y install dnf-plugins-core && \
    dnf config-manager \
        --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo && dnf clean all

RUN dnf install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    ruby \
    ruby-devel \
    make \
    gcc \
    && dnf clean all

WORKDIR /chainsafe

COPY Gemfile Gemfile.lock health_check.sh sync_check_process.rb sync_check.rb sync_check.toml ./
COPY ruby_common ruby_common

RUN gem install bundler && bundle install
