---
- name: Update packages
  ansible.builtin.command: sudo apt update
  changed_when: false

- name: Install certbot
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Allow nginx full
  become: true
  community.general.ufw:
    rule: allow
    name: "Nginx Full"
    state: enabled

- name: Delete Nginx HTTP
  community.general.ufw:
    rule: deny
    name: 'Nginx HTTP'

- name: Remove default nginx config
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Install system nginx config
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0755"

- name: Check if the url file exist
  ansible.builtin.stat:
    path: /etc/nginx/sites-enabled/http
  register: letsencrypt_http_file_exist
  changed_when: false

- name: Install nginx url for certbot requests
  ansible.builtin.template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/sites-enabled/http
    mode: "0755"
  when: not letsencrypt_http_file_exist.stat.exists

- name: Reload nginx to activate certbot endpoints
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Create certbot certificate
  ansible.builtin.command: certbot --nginx  -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: Generate dhparams
  ansible.builtin.command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified files
  ansible.builtin.template:
    src: templates/nginx-le.j2
    dest: /etc/nginx/sites-enabled/le
    mode: "0755"

- name: Reload nginx to activate specified endpoints
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Add certbot cronjob for cert renewal
  become: true
  ansible.builtin.cron:
    name: certbot_renewal
    special_time: weekly
    job: "certbot renew --nginx && service nginx reload"
