global:
  slack_api_url: "https://hooks.slack.com/services/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" 

route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match: 
      severity: warning
    receiver: 'warning-notifications'  
  - match:
      severity: critical
    receiver: 'critical-notifications'
  - match:
      alertname: InstanceDown
  receiver: 'alert-team'

receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#zeitgeist-operation"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
- name: 'critical-notifications'
  slack_configs:
  - channel: "#zeitgeist-operation"
    text: "Critical alert: {{ .CommonAnnotations.summary }}: {{ .CommonAnnotations.description }}"   
- name: 'warning-notifications'
  slack_configs:
  - channel: "#zeitgeist-operation"
    text: "Warning alert: {{ .CommonAnnotations.summary }}: {{ .CommonAnnotations.description }}"     


