digitalocean_token = ""
source_addresses = ["0.0.0.0/0", "::/0"]
destination_addresses = ["0.0.0.0/0", "::/0"]
region = "fra1"
backups = "true"
image = "docker-20-04"
size = "so-2vcpu-16gb"
name = "forest-iac"
new_key_ssh_key_fingerprint = "" 
firewall_name = ""