digitalocean_token = ""
source_addresses = ["0.0.0.0/0", "::/0"]
destination_addresses = ["0.0.0.0/0", "::/0"]
region = "fra1"
backups = "false"
image = "docker-20-04"
size = "s-4vcpu-8gb"
name = "forest-calibnet-iac"
new_key_ssh_key_fingerprint = "" 
firewall_name = ""