variable "digitalocean_token" {}
variable "image" {}
variable "name" {}
variable "region" {}
variable "size" {}
variable "backups" {}
variable "source_addresses" {}
variable "new_key_ssh_key_fingerprint" {}
variable "destination_addresses" {}
variable "firewall_name" {}
variable "observability_name" {}
variable "protocol" {}