FROM fedora:36

LABEL org.opencontainers.image.source https://github.com/chainsafe/forest-iac

# Install dependencies
RUN dnf -y install \
    docker \
    docker-compose \
    ruby \
    ruby-devel \
    make \
    gcc \
    && dnf clean all

# Gem install dependencies
RUN gem install \
    docker-api \
    slack-ruby-client \
    sys-filesystem

# Set a working directory and copy files
WORKDIR /chainsafe
COPY ruby_common ruby_common
COPY sync_check/* ./

# Use shell form of ENTRYPOINT
ENTRYPOINT ["/bin/bash", "run_service.sh"]
