FROM fedora:36

LABEL org.opencontainers.image.source https://github.com/chainsafe/forest-iac

# Install dependencies
RUN dnf -y install \
    docker \
    docker-compose \
    ruby \
    ruby-devel \
    make \
    gcc \
    s3fs-fuse \
    && dnf clean all

# Gem install dependencies
RUN gem install \
    docker-api \
    slack-ruby-client \
    activesupport

# Set a working directory and copy files
WORKDIR /usr/src/app
COPY ruby_common ruby_common
COPY daily_snapshot/*.rb daily_snapshot/upload_snapshot.sh daily_snapshot/run_service.sh ./

# Use shell form of ENTRYPOINT
ENTRYPOINT ["/bin/bash", "run_service.sh"]
