FROM fedora:36

LABEL org.opencontainers.image.source="https://github.com/chainsafe/forest-iac"

# Install dependencies
RUN dnf install -y \
    docker \
    docker-compose \
    ruby \
    ruby-devel \
    make \
    gcc \
    s3fs-fuse \
    && dnf clean all

# Pin gem versions and install
RUN gem install \
    docker-api:1.34.2 \
    slack-ruby-client:0.15.0 \
    activesupport:6.1.4

# Set working directory and copy files
WORKDIR /usr/src/app
COPY ruby_common /app/ruby_common
COPY daily_snapshot/*.rb daily_snapshot/upload_snapshot.sh daily_snapshot/run_service.sh /app/

# Use shell form of ENTRYPOINT
ENTRYPOINT ["/bin/bash", "run_service.sh"]