name = "forest-latest-snapshot"
main = "./src/index.ts"

compatibility_date = "2022-06-30"
logpush = true
node_compat = true

routes = [
    { pattern = "forest-archive.chainsafe.dev/latest/calibnet", zone_name = "chainsafe.dev" },
    { pattern = "forest-archive.chainsafe.dev/latest/mainnet", zone_name = "chainsafe.dev" },
    { pattern = "forest-archive.chainsafe.dev/latest/calibnet/", zone_name = "chainsafe.dev" },
    { pattern = "forest-archive.chainsafe.dev/latest/mainnet/", zone_name = "chainsafe.dev" },

#		below endpoints are for the archive
		{ pattern = "forest-archive.chainsafe.dev/archive/calibnet/*", zone_name = "chainsafe.dev" },
		{ pattern = "forest-archive.chainsafe.dev/archive/mainnet/*", zone_name = "chainsafe.dev" },
		{ pattern = "forest-archive.chainsafe.dev/archive/historical/*", zone_name = "chainsafe.dev" }
]

[[r2_buckets]]
binding = 'FOREST_ARCHIVE'     # can be any valid JavaScript variable name
bucket_name = 'forest-archive'
preview_bucket_name = 'forest-archive-dev'
