---
# defaults file for role/observability
install_docker_compose: ""
docker_compose_version: "v2.16.0"
docker_compose_path: /usr/local/bin/docker-compose

prometheus_retention_time: "365d"
prometheus_scrape_interval: "30s"
prometheus_node_exporter: true
forest_exporter: "forest"
observability: "observability"
prometheus_env: "observability"
prometheus_var_config:
  global:
    scrape_interval: "{{ prometheus_scrape_interval }}"
    evaluation_interval: 5s
    external_labels:
      env: '{{ prometheus_env }}'
  scrape_configs:
    - job_name: prometheus
      scrape_interval: 5m
      static_configs:
        - targets: ['{{ inventory_hostname }}:9090']

user: "chainsafe"
user_group: "{{ user }}"

endpoint: nyc3.digitaloceanspaces.com
bucketname: "{{ groups['spaces'][0] }}"
region: nyc3
loki_config_directory: /home/observability/loki
loki_config_auth: true
loki_config_retention: 336h
loki_config_period: 168h
loki_config_http_port: 3100

slack_api_url: "https://hooks.slack.com/services/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"
channel: "monitoring-alerts-forest"



