---
- name: Set-up Node-exporter
  hosts: all
  gather_facts: false
  become: true
  roles:
    - node_exporter

- name: Set-up Loki-Prometheus-Grafana
  gather_facts: false
  hosts: observability
  become: true
  roles:
    - observability
  vars:
    spaces_endpoint: "fra1.digitaloceanspaces.com"
    spaces_region: "us-west-1"
    spaces_bucket_name: ""
    slack_channel: ""
    spaces_access_token: ""
    spaces_secret_key: ""
    slack_token: ""
    domain_name: ""
