---
- name: Create a login user
  ansible.builtin.user:
    name: "{{ user }}"
    state: present

- name: Create .ssh directory for created user
  become: true
  ansible.builtin.file:
    path: "{{ user_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"

- name: Copy public key from existing root to new user
  become: true
  ansible.builtin.copy:
    src: "/root/.ssh/authorized_keys"
    dest: "{{ user_dir_auth }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
    mode: "0600"

- name: Restart SSHD
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Allow created user to log in
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ user }}'
    state: present

- name: Add user to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add new user to "docker" group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Start the docker container
  become: true
  become_user: "{{ user }}"
  community.general.docker_container:
    name: forest
    image: ghcr.io/chainsafe/forest:latest
    state: started
    restart_policy: always
    command: --encrypt-keystore false --auto-download-snapshot --chain calibnet --loki --loki-endpoint "{{ loki_endpoint }}"
    pull: true
    ports:
      - "1234:1234"
      - "6116:6116"
      - "3100:3100"
  register: forest_container_result

- name: Get infos on container
  become_user: "{{ user }}"
  community.docker.docker_container_info:
    name: forest
  register: forest_result

- name: Does container exist?
  become_user: "{{ user }}"
  ansible.builtin.debug:
    msg: "The container {{ 'exists' if forest_result.exists else 'does not exist' }}"

- name: Print information about container
  become_user: "{{ user }}"
  ansible.builtin.debug:
    var: forest_result.container
  when: forest_result.exists
