---
# tasks file for role/forest
- name: Create a login user
  user:
    name: "{{ user }}"
    state: present 

- name: Create .ssh directory for created user
  become: true
  file:
    path: "{{ user_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700 

- name: Copy public key from existing root to new user
  become: true
  copy:
    src: "/root/.ssh/authorized_keys"
    dest: "{{ user_dir_auth }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: yes
    mode: 0600

- name: Allow new user to log in
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ user }}'
    state: present

- name: Restart SSHD Service 
  become: true
  shell: sudo service ssh restart 

- name: Add {{ user }} to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create docker user
  user:
    name: '{{ user }}'
    append: true
    shell: /bin/bash
    system: true
    create_home: false

- name: Add new user to "docker" group
  user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Run the Docker command
  become: yes
  become_user: "{{ user }}"
  shell: docker run -p 1234:1234 --rm --detach ghcr.io/chainsafe/forest:latest --encrypt-keystore false --auto-download-snapshot --chain calibnet 
    
- name: Ensure app is running
  shell: ps aux | grep forest
  register: app_status
- debug: msg={{app_status.stdout_lines}}
