---
# tasks file for role/forest
- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Create a login user
  user:
    name: "{{ user }}"
    state: present

- name: Add public key to authorized_keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '~/sammy.pub') }}"

- name: Allow specific users to log in
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers {{ user }}'
    state: present

- name: Restart SSHD Service 
  become: true
  shell: sudo service ssh restart 

- name: Add {{ user }} to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ user }}'
    line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create docker user
  user:
    name: '{{ user }}'
    append: true
    shell: /bin/bash
    system: true
    create_home: false

- name: update all packages 
  become: true
  shell: 
    cmd: sudo apt update 

- name: Add docker users to "docker" group
  user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Run the Docker command
  become: yes
  become_user: "{{ user }}"
  shell: docker run -p 1234:1234 -p 6116:6116 --rm --detach ghcr.io/chainsafe/forest:latest --encrypt-keystore false --auto-download-snapshot --chain calibnet
    
- name: Ensure app is running
  shell: ps aux | grep forest
  register: app_status
- debug: msg={{app_status.stdout_lines}}
