---
# defaults file for role/observability
docker_compose_version: "v2.16.0"
docker_compose_path: /usr/local/bin/docker-compose

prometheus_scrape_interval: "30s"
prometheus_node_exporter: true
forest_exporter: "forest"
observability: "observability"
prometheus_env: "observability"
prometheus_var_config:
  global:
    scrape_interval: "{{ prometheus_scrape_interval }}"
    evaluation_interval: 5s
    external_labels:
      env: '{{ prometheus_env }}'
  scrape_configs:
    - job_name: prometheus
      scrape_interval: 5m
      static_configs:
        - targets: ['localhost:9090']
user: "forest"
user_group: "{{ user }}"
user_dir: /home/forest/.ssh
user_dir_auth: /home/forest/.ssh/authorized_keys

loki_config_retention: 336h
loki_config_period: 168h
loki_config_http_port: 3100
loki_ingester_chunk_idle_period: 5m
loki_schema_version: v11
loki_from_date: 2022-01-01
spaces_access_token: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
spaces_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
slack_channel: "{{ lookup('env', 'SLACK_CHANNEL') }}"
spaces_endpoint: "{{ lookup('env', 'SPACES_ENDPOINT') }}"
spaces_region: "{{ lookup('env', 'SPACES_REGION') }}"
slack_token: "{{ lookup('env', 'SLACK_TOKEN') }}"
