#!/bin/bash
cd "$BASE_FOLDER" || exit
# shellcheck source=/dev/null
source .bashrc
flock -n /tmp/calibnet.lock -c "ruby daily_snapshot.rb calibnet > calibnet_log.txt 2>&1"
flock -n /tmp/calibnet.lock -c "./upload_filops_snapshot.sh calibnet > filops_calibnet_log.txt 2>&1"
