name: Deploy Snapshot Service and Set-up New Relic Agent


on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy-daily-snapshot-calibnet:
    name: snapshot service (calibnet)
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/terraform
        with:
          digitalocean_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          working_directory: daily_snapshot_terraform
          chain: Snapshot Service

  setup-newrelic-agent-using-ansible:
    name: Set-up New Relic Agent on Forest Snapshot Service Infrastructure with Ansible
    runs-on: ubuntu-latest
    needs: deploy-daily-snapshot-calibnet
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    # Using Custom Composite action in ./composite-action/ansible folder
      - name: Composite Action for Infrastruture Droplets with ansible
        uses: ./composite-action/ansible
        with:
          working_directory: ansible
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
