name: Deploy Forest Calibnet Infrastructure and Set-up New Relic Agent

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Terraform/**'
      - 'ansible/**'
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy-forest-calibnet-infrastruture-with-terraform:
    name: Deploy Forest Terraform calibnet Infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/terraform
        with:
          digitalocean_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          working_directory: terraform/calibnet
          chain: calibnet

  setup-newrelic-agent-using-ansible:
    name: Set-up New Relic Agent on Forest Calibnet Infrastructure with Ansible
    runs-on: ubuntu-latest
    needs: deploy-forest-calibnet-infrastruture-with-terraform
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    # Using Custom Composite action in ./composite-action/ansible folder
      - name: Composite Action for Infrastruture Droplets with ansible
        uses: ./composite-action/ansible
        with:
          working_directory: ansible
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
