name: Export archival snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - 'ansible/archival-snapshots/**'
  push:
    paths:
      - 'ansible/archival-snapshots/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install Cloudflared
        run: |
          curl -O https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz
          tar -xvf cloudflared-stable-linux-amd64.tgz
          sudo cp ./cloudflared /usr/local/bin/
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH key
        run: ssh -o ProxyCommand='/usr/local/bin/cloudflared access ssh --hostname %h' archie.chainsafe.dev "echo 'SSH connection successful'"
