name: Forest Mainnet

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy-forest-mainnet:
    name: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/terraform
        with:
          do_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          working_directory: terraform/forest-mainnet
          environment: Mainnet
          new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          nr_license_key: ${{ secrets.NR_LICENSE_KEY }}
          new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}

