on:
  pull_request:
    branches:
      - main
    paths:
      - 'tf-managed/modules/forest-droplet/**'
      - 'tf-managed/live/environments/prod/applications/forest-mainnet/**'
    # This needs to be declared explicitly so that the job is actually
    # run when moved out of draft.
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths:
      - 'tf-managed/modules/forest-droplet/**'
      - 'tf-managed/live/environments/prod/applications/forest-mainnet/**'
  workflow_dispatch:

jobs:
  deploy-forest-mainnet:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # Using Custom Composite action in ./composite-action/terragrunt folder
      - name: Composite Action for Deploying Terragrunt Resources
        uses: ./composite-action/terragrunt
        with:
          do_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          working_directory: tf-managed/live/environments/prod/applications/forest-mainnet
          service_name: forest-mainnet
          max_retries: '5'
          retry_delay_seconds: '60s'
          new_relic_account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
