name: Deploy and Configure Forest Mainnet Infrastructure
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy-forest-mainnet-infrastruture-with-terraform:
    name: Deploy Forest Terraform Mainnet Infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

        # Using Custom Composite action in ./composite-action/terraform folder
      - name: Calibnet Composite
        uses: ./composite-action/terraform
        with:
          digitalocean_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          working_directory: terraform/mainnet
          environment: mainnet

  configure-forest-infrastructure-mainnet-using-ansible:
    name: Configure Forest Mainnet Infrastructure with Ansible
    runs-on: ubuntu-latest
    needs: deploy-forest-mainnet-infrastruture-with-terraform
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

                # Using Custom Composite action in ./composite-action/ansible folder
      - name:
        uses: ./composite-action/ansible
        with:
          working_directory: ansible
          environment: mainnet
          domain_name: forest-mainnet.chainsafe.io
          spaces_bucket_name: forest-mainnet-loki-logs
          slack_channel: forest-mainnet-monitoring
          volume_name: "forest_mainnet_volume"
          slack_token: ${{ secrets.SLACK_TOKEN }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
