name: Deploy Forest Mainnet and Calibnet Infrastructure
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy-forest-mainnet-infrastruture-with-terraform:
    name: Deploy Forest Terraform Mainnet Infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

        # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Mainnet
        uses: ./composite-action/terraform
        with: Composite Action for Mainnet
          digitalocean_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          working_directory: terraform/mainnet
          environment: mainnet

  deploy-forest-calibnet-infrastruture-with-terraform:
    name: Deploy Forest Terraform Calibnet Infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Calibnet
        uses: ./composite-action/terraform
        with:
          digitalocean_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          working_directory: terraform/calibnet
          environment: calibnet
