name: Deploy Snapshot Service


on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy-daily-snapshot-calibnet:
    name: snapshot service (calibnet)
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/terraform
        with:
          do_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          working_directory: daily_snapshot_terraform
          environment: Snapshot Service
