---
name: Deploy Sync Check Service

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sync-check:
    name: sync check service
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

       # Using Custom Composite action in ./composite-action/terraform folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/terraform
        with:
          do_token: ${{ secrets.DO_TOKEN }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          working_directory: sync_check_terraform/
          chain: Sync Check Service

  setup-newrelic-agent-using-ansible:
    name: Set-up New Relic Agent on Forest Sync Check Infrastructure with Ansible
    runs-on: ubuntu-latest
    needs: sync-check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    # Using Custom Composite action in ./composite-action/ansible folder
      - name: Composite Action for Infrastruture Droplets with Ansible
        uses: ./composite-action/ansible
        with:
          working_directory: ansible
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
