name: Build and publish Forest IAC Docker image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-snapshot-iac-image:
    name: Build Docker Infrastructure image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build daily snapshot image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: scripts/
          file: scripts/Dockerfile-snapshot
          tags: |
            ghcr.io/chainsafe/sync-snapshot:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Daily snapshot Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build sync check image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: scripts/
          file: scripts/Dockerfile-sync-check
          tags: |
            ghcr.io/chainsafe/sync-check:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Sync check Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
