name: Build and publish Forest IAC Docker image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-snapshot-iac-image:
    name: Build Docker Infrastructure image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/chainsafe/sync-check
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD'}}-{{sha}}

      - name: Build sync check image and push to GitHub Container Registry
        id: build-sync-check
        uses: docker/build-push-action@v4
        with:
          context: scripts/
          file: scripts/Dockerfile-sync-check
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main'}}
