name: 'Hadolint Linting'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: "Dockerfile*"
        recursive: true
        # Ignore https://github.com/hadolint/hadolint/wiki/DL3041
        # Ignore https://github.com/hadolint/hadolint/wiki/DL3028
        # Ignore https://github.com/hadolint/hadolint/wiki/DL3050

        ignore: DL3041,DL3050,DL3028
