name: 'Hadolint Linting'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: "Dockerfile*"
        recursive: true
        # don't pin versions in dependencies
        ignore: DL3041,DL3028
