name: 'Hadolint Linting'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: hadolint/hadolint-action@v3.3.0
      with:
        dockerfile: "Dockerfile*"
        recursive: true
        # don't pin versions in dependencies
        ignore: DL3028,DL3008,DL3018
