name: 'Linting'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
           path: ~/.tflint.d/plugins
           key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
           tflint_version: v0.44.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive

  fmt_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Show version
        run: terraform --version

      - name: Check formatting
        run: terraform fmt -check -diff -recursive
