name: Mirror Builtin Actors Releases
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  pull_request:
    paths:
      - 'scripts/mirror-actors/**'
  push:
    paths:
      - 'scripts/mirror-actors/**'
  workflow_dispatch:

jobs:
  mirror-releases-do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run tests
        working-directory: scripts/mirror-actors
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          source .venv/bin/activate
          python3 mirror_actors/
        env:
            SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_CHANNEL: "#forest-notifications"
            BUCKET_NAME: filecoin-builtin-actors
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            REGION_NAME: fra1

  # mirror-releases-cf:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Set up S3cmd cli tool for Cloudflare
  #       uses: s3-actions/s3cmd@v1.5.0
  #       with:
  #         provider: cloudflare
  #         region: auto
  #         access_key: ${{ secrets.R2_ACCESS_KEY }}
  #         secret_key: ${{ secrets.R2_SECRET_KEY }}
  #         account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  #     - name: Run script to mirror to Cloudflare
  #       working-directory: scripts
  #       if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
  #       run: bash ./mirror-builtin-actors.sh
  #       env:
  #           SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
  #           SLACK_CHANNEL: "#forest-notifications"
  #           BUCKET_NAME: filecoin-builtin-actors
