name: Mirror Builtin Actors Releases
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  pull_request:
    paths:
      - 'scripts/mirror-actors/**'
  push:
    paths:
      - 'scripts/mirror-actors/**'
  workflow_dispatch:

jobs:
  mirror-releases-do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        working-directory: scripts/mirror-actors
        run: poetry install --no-interaction --no-root

      - name: Run tests
        working-directory: scripts/mirror-actors
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          source .venv/bin/activate
          python3 mirror_actors/
        env:
            SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_CHANNEL: "#forest-notifications"
            BUCKET_NAME: filecoin-builtin-actors
            AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            REGION_NAME: fra1
            ENDPOINT_URL: https://fra1.digitaloceanspaces.com

  mirror-releases-cf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        working-directory: scripts/mirror-actors
        run: poetry install --no-interaction --no-root

      - name: Mirror Actors to CloudFlare
        working-directory: scripts/mirror-actors
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          source .venv/bin/activate
          python3 mirror_actors/
        env:
            SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_CHANNEL: "#forest-notifications"
            BUCKET_NAME: filecoin-builtin-actors
            AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}
            REGION_NAME: "auto"
            ENDPOINT_URL: "https://2238a825c5aca59233eab1f221f7aefb.r2.cloudflarestorage.com"
