name: Scripts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      env:
        SHELLCHECK_OPTS: --external-sources
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Run rubocop
        run: |
          gem install rubocop --no-document --version 1.60.1
          rubocop
  run-js-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        yarn install
        yarn lint
        yarn js-check
