name: Scripts

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      env:
        SHELLCHECK_OPTS: --external-sources
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Run rubocop
        run: |
          gem install rubocop --no-document
          rubocop scripts/ # TODO: Apply rubocop to terraform/modules/
  run-js-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        yarn install
        yarn lint
        yarn js-check
  run-py-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true

    # - name: Install dependencies
    #   working-directory: scripts/mirror-actors
    #   run: poetry install --no-interaction --no-root

    - name: Lint Python Code
      working-directory: scripts/mirror-actors
      run: poetry run pylint mirror_actors/ -f actions
