
install:
	@doctl serverless install

con_link:
	@doctl serverless connect snapshots

con_spaces:
	@doctl serverless connect monitor-spaces

deploy_link:
	@doctl serverless deploy snapshot_function

deploy_snap:
	@doctl serverless deploy monitor_snapshots --remote-build
